### ISSUE TITLE
Structurizr as a dependency or change the download directory?

### ISSUE THREAD

**Issue by dzeigler** [jakzal/gradle-structurizr-cli#65]
Is there any support for defining structurizr-cli as a gradle dependency, which would allow downloading the cli zip from the local gradle cache? Or alternatively, is there a way to set the directory where the cli is downloaded or extracted to so that it's outside the build directory? 

I ask because gradle clean wipes out the build/structurizr-cli directory by default and leads to a redownload, which can be slow.

Thanks!

**Comment by jakzal** [comment]
At the moment the download task always downloads to the build directory:

https://github.com/jakzal/gradle-structurizr-cli/blob/911c4d66113e57b9fb1c164ff89a976348a78ebc/src/main/kotlin/pl/zalas/gradle/structurizrcli/StructurizrCliPlugin.kt#L43

It should be easy enough to make it configurable.

Is your only concern the need to re-download, or do you also have another use case in mind? I didn't quite get the "as a gradle dependency" part.

**Comment by dzeigler** [comment]
My only concern was redownloading.

I was just wondering if there were an option to leverage gradle dependency
resolution for downloading the cli. For example, if structurizr-cli were
defined as a dependency of the plugin, then gradle could manage downloading
it or pulling from the local cache if it were already downloaded.

It sounds like making the download directory configurable is simple though.

Thanks again!

**Comment by jakzal** [comment]
@dzeigler would you mind reviewing https://github.com/jakzal/gradle-structurizr-cli/pull/66 to see if that's what you expected?

**Comment by jakzal** [comment]
> I was just wondering if there were an option to leverage gradle dependency
> resolution for downloading the cli. For example, if structurizr-cli were
> defined as a dependency of the plugin, then gradle could manage downloading
> it or pulling from the local cache if it were already downloaded.

Btw, this kinda happens already. Unless you invoke the clean task, the zip file and the extracted structurizr jar should remain in the build folder to be used in consecutive builds.

**Comment by dzeigler** [comment]
> @dzeigler would you mind reviewing #66 to see if that's what you expected?

Looks great!

**Comment by jakzal** [comment]
Shipped as [1.3.0](https://github.com/jakzal/gradle-structurizr-cli/releases/tag/1.3.0).
